// HUD
optOcultarHUD = "Ocultar toda la HUD",
optOcultarAutomaticamenteHUD = "Ocultar automaticamente la HUD cuando la barra este llena.",
optOcultarAutomaticamenteVida = "Ocultar automaticamente la vida cuando la barra este llena.",
optEstaminaDerecha = "Poner la barra de estamina a la derecha.",
optColorVida = "Color de la Vida.",
optColorEscudo = "Color del Escudo.",
optColorHambre = "Color del Hambre.",
optColorSed = "Color de la Sed.",
optColorEstamina = "Color de la Estamina.",